### ISSUE TITLE
pg94 thru pg11 support (patches applied) and a new release

### ISSUE THREAD

**Issue by lussman3** [dvarrazzo/pgmp#13]
This is still a very useful project I'd love to see it come back alive.   Daniel you could please reach out to me and we can figure out how to make it worth your while.  Note that I am also a fan of your work on psycopg2.  :-)

--Denis Lussier
   Product Manager, AWS Postgres Engines Group
   luss@amazon.com

**Comment by dvarrazzo** [comment]
Hello,

Thank you for your interest. The disappointing suppression of pgfoundry and the limited feedback have reduced my enthusiasm in this project, but if there is still interest I don't intend abandon it.

The project should have the outstanding bugs fixed and should support all the currently maintained versions of postgres. In order to consider the project "alive" all the supported versions should be tested on travis, and documentation should be published automatically on commit as github pages.

I do believe Amazon has slightly more resources than my humble self, who is maintaining project you use actively (psycopg, pg_repack, now I know this one) without having received anything back. I'm pretty sure a couple of your million of employers could help actively with those.

If you provide comprehensive merge requests for the above tasks I'll be happy to release a new version immediately. If you want me to do it myself, you can provide compensation at market price for the work, otherwise I'm afraid pgmp is pretty low in my priorities at the moment.

Regards,

-- Daniele

**Comment by lussman3** [comment]
Hi Daniele,

I only recently joined AWS and am a long time Postgres community guy.
Compensation, at market price, for you to do additional work on one or more
of your well known and high quality projects is definitely on the table.
  Perhaps we can talk on the phone later this week at your convenience.
You can text me at the below and we could arrange a time.

--Luss
  +1-973-309-2230

**Comment by df7cb** [comment]
> If you provide comprehensive merge requests for the above tasks I'll be happy to release a new version immediately. If you want me to do it myself, you can provide compensation at market price for the work, otherwise I'm afraid pgmp is pretty low in my priorities at the moment.

Hi,

I opened PRs to support 9.5 (#8) and 10 (#11) in 2016 and 2017. Please consider merging them :)

Christoph

**Comment by dvarrazzo** [comment]
@df7cb will do, thank you

**Comment by df7cb** [comment]
Ping!

**Comment by dvarrazzo** [comment]
Pong. Let's see in which form this project can be revived

**Comment by df7cb** [comment]
That would be nice. The stack of patches in the Debian package has grown a bit too high over time:
https://salsa.debian.org/postgresql/postgresql-pgmp/tree/master/debian/patches
It would be nice to see them merged or resolved otherwise.

**Comment by dvarrazzo** [comment]
@df7cb I think the queue can now shrink: I have applied your long due patches, and also made the build reproducible in 7914a79 (your current patch likely won't apply anymore).

master and maint-1.0 now work, based on a quick test. I will run a full test grid on all the supported postgres versions and release 1.0.3.

@lussman3 I haven't got around yet to set up a support page, but you are [welcome to contribute](https://www.paypal.me/dvarrazzo).

**Comment by dvarrazzo** [comment]
pgmp 1.0.3 [tagged](https://github.com/dvarrazzo/pgmp/tree/rel-1.0.3) and [released on PGXN](https://pgxn.org/dist/pgmp/).
